apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  replicas: 4
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: karthequian/helloworld:latest
        ports:
        - name: default
          containerPort: 80
        resources:
        livenessProbe:
           initialDelaySeconds: 60
           periodSeconds: 5
           httpGet:
            path: /
            port: default  
        env:
            - name: v
              value: "0.1"     

---
apiVersion: v1
kind: Service
metadata:
  name: helloworldapi
spec:
  selector:
    app: helloworld
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

  type: LoadBalancer


 